name: cmt

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version
        run: |
          if [ ! -f version.txt ]; then
            echo "1.0.0" > version.txt
          fi

          version=$(cat version.txt)
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          patch=$(echo $version | cut -d. -f3)

          patch=$((patch + 1))
          if [ $patch -ge 100 ]; then
            patch=0
            minor=$((minor + 1))
          fi
          if [ $minor -ge 100 ]; then
            minor=0
            major=$((major + 1))
          fi

          echo "$major.$minor.$patch" > version.txt

      - name: Commit & Push
        run: |
          git config user.name "johnydepp1921"
          git config user.email "johnydepp1921@gmail.com"
          git add .
          git commit -m "bump version to $(cat version.txt)"
          git push
